version: '3'
services:
        database:
                image: mysql:5.7.29
                volumes:
                        - sql_storage:/var/lib/mysql  
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: saraplay
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: mypro
        client:
                image: nginx
                ports:
                        - 1601:80
                volumes:
                        - ./docker-html:/usr/share/nginx/html                
        joomla:
                image: joomla:latest
                restart: always
                depends_on:
                        - database
                ports:
                        - 8082:80
                environment:
                        JOOMLA_DB_HOST: database
                        JOOMLA_DB_USER: saraplay
                        JOOMLA_DB_PASSWORD: redhat
                        JOOMLA_DB_NAME: mypro
                volumes:
                        - joomla_storage:/var/www/html
        ghost:
                image: ghost:1-alpine
                restart: always
                depends_on:
                        - database
                ports:
                        - 8083:2368
                environment:
                        database_client: mysql
                        database_connection_host: database
                        database_conection_user: saraplay
                        database_connection_password: redhat
                        database_connection_database: mypro
                volumes:
                        - ghost_storage:/var/lib/ghost
        owncloud:
                image: owncloud
                restart: always
                depends_on:
                        - database
                ports:
                        - 8081:80
                volumes:
                        - owncloud_storage:/var/www/html

        wordpress:
                image: wordpress:5.1.1-php7.3-apache
                restart: always
                depends_on:
                        - database
                ports:
                        - 8084:80
                environment:
                        WORDPRESS_DB_HOST: database
                        WORDPRESS_DB_USER: saraplay
                        WORDPRESS_DB_PASSWORD: redhat
                        WORDPRESS_DB_NAME: mypro
                volumes:
                        - wordpress_storage:/var/www/html
        nextcloud:
                image: nextcloud:latest
                restart: always
                depends_on:
                        - database
                ports:
                        - 8085:80
                volumes:
                        - nextcloud_storage:/var/www/html

        drupal:
                image: drupal:latest
                restart: always
                depends_on:
                        - database
                ports:
                        - 8086:80
                volumes:
                        - drupal_storage:/var/www/html

volumes:
        sql_storage:
        joomla_storage:
        ghost_storage:
        owncloud_storage:
        wordpress_storage:
        nextcloud_storage:
        drupal_storage:
